name: ddqn_pt
channels:
  - conda-forge
dependencies:
  - jupyterlab=3.2.4
  - matplotlib=3.5.0
  - numpy=1.21.4
  - pandas=1.3.4
  - pip=21.0.1
  - python=3.8.8
  - pytorch=1.10.0
  - scipy=1.7.3
  - pip:
    - gym==0.21.0
